import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { extname, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const TEXT_EXTENSIONS = new Set([".css", ".html", ".js", ".json", ".md", ".mjs", ".yaml", ".yml"]);
const EXCLUDED_PATHS = new Set(["tests/repository-content.contract.test.mjs"]);

const VIETNAMESE_DIACRITICS = /[ÀÁẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬĐÈÉẺẼẸÊẾỀỂỄỆÌÍỈĨỊÒÓỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÙÚỦŨỤƯỨỪỬỮỰỲÝỶỸỴàáảãạăắằẳẵặâấầẩẫậđèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵ]/u;
const VIETNAMESE_DIACRITIC_CHARACTERS = "ÀÁẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬĐÈÉẺẼẸÊẾỀỂỄỆÌÍỈĨỊÒÓỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÙÚỦŨỤƯỨỪỬỮỰỲÝỶỸỴàáảãạăắằẳẵặâấầẩẫậđèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵ";
const ROMANIZED_VIETNAMESE = /\b(?:ung dung|ghi chu|muc tieu|tai lieu|khong duoc|bat buoc|bao mat|hieu nang|khoi tao|kiem tra|thay doi|trang thai|yeu cau|phuc hoi|nguoi dung|cong viec|hoan tat|du lieu|tinh nang|phim tat)\b/i;
const TOOL_PROVENANCE = /(?:docs\/superpowers|AI_AGENT_RULES|agentic workers|superpowers:|\bCodex\b|\bChatGPT\b|\bClaude Code\b|generated by (?:an? )?AI|AI[- ]assisted coding)/i;

function trackedTextFiles() {
  return execFileSync("git", ["ls-files", "-z"], { cwd: ROOT, encoding: "utf8" })
    .split("\0")
    .filter(Boolean)
    .filter((path) => TEXT_EXTENSIONS.has(extname(path)))
    .filter((path) => !EXCLUDED_PATHS.has(path));
}

function findViolations(pattern, label) {
  const violations = [];
  for (const path of trackedTextFiles()) {
    const content = readFileSync(resolve(ROOT, path), "utf8");
    const match = content.match(pattern);
    if (match) {
      violations.push(`${path}: ${label} (${JSON.stringify(match[0])})`);
    }
  }
  return violations;
}

test("Vietnamese diacritic detector covers every Vietnamese letter variant", () => {
  for (const character of VIETNAMESE_DIACRITIC_CHARACTERS) {
    assert.match(character, VIETNAMESE_DIACRITICS, `missing Vietnamese character ${character}`);
  }
});

test("tracked repository text is English-only", () => {
  const violations = [
    ...findViolations(VIETNAMESE_DIACRITICS, "Vietnamese diacritic"),
    ...findViolations(ROMANIZED_VIETNAMESE, "romanized Vietnamese phrase"),
  ];

  assert.deepEqual(violations, [], violations.join("\n"));
});

test("tracked repository text contains no tool-specific provenance markers", () => {
  const violations = findViolations(TOOL_PROVENANCE, "tool-specific provenance marker");
  assert.deepEqual(violations, [], violations.join("\n"));
});
